[project]
name = "PosiTron"
version = "0.1.0"
description = "Implenment Attention is All you need paper with different positional encodings"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.4.1",
    "tqdm>=4.67.0"]





